### Trade signals
POST http://127.0.0.1:8001/api/v1/discord/signal
Content-Type: application/json

{
    "timestamp": "2025-08-05T14:52:32.979Z",
    "content": "⁠⁣⁣⁠⁣⁣⁠⁠⁢⁠⁣⁣⁠⁣⁣⁣⁣⁢⁠⁣⁣⁣⁠⁠⁣⁠⁢⁠⁣⁣⁠⁠⁣⁠⁠⁢⁠⁣⁣⁠⁣⁣⁣⁠⁢⁠⁣⁣⁠⁠⁠⁠⁣⁢⁠⁣⁣⁠⁣⁠⁠⁠⁢⁠⁣⁣⁠⁠⁣⁠⁣⁢⁠⁣⁣⁠⁠⁣⁠⁣⁢⁠⁣⁣⁠⁠⁣⁠⁠Eth entry 3563-3510 sl 3430",
    "structured": "ETH|Entry:|3563-3510|S⁠⁣⁣⁠⁣⁣⁠⁠⁢⁠⁣⁣⁠⁣⁣⁣⁣⁢⁠⁣⁣⁣⁠⁠⁣⁠⁢⁠⁣⁣⁠⁠⁣⁠⁠⁢⁠⁣⁣⁠⁣⁣⁣⁠⁢⁠⁣⁣⁠⁠⁠⁠⁣⁢⁠⁣⁣⁠⁣⁠⁠⁠⁢⁠⁣⁣⁠⁠⁣⁠⁣⁢⁠⁣⁣⁠⁠⁣⁠⁣⁢⁠⁣⁣⁠⁠⁣⁠⁠L:|3430|Disclaimer|We recommend|not to risk more than 1-3%|of your account per trade. This means the amount you lose if stops are hit.  Additionally, avoid taking more than 2-3 losses per day. If you risk more, you could lose your entire account."    
}

### Alert signals
POST http://127.0.0.1:8001/api/v1/discord/signal/update
Content-Type: application/json

{
    "discord_id": "1402291624624652469",
    "trader": "@Woods",
    "trade": "1402272321452118078",
    "timestamp": "2025-08-05T14:06:16.629Z",
    "content": " BTC ⁠🚀｜trades⁠: Stopped BE @Woods"
}

