### Trade signals
POST http://127.0.0.1:8001/api/v1/discord/signal
Content-Type: application/json

{
    "timestamp": "2025-08-06T10:44:39.614Z",
    "content": "longe⁠⁣⁣⁠⁣⁣⁠⁠⁢⁠⁣⁣⁠⁣⁣⁣⁣⁢⁠⁣⁣⁣⁠⁠⁣⁠⁢⁠⁣⁣⁠⁠⁣⁠⁠⁢⁠⁣⁣⁠⁣⁣⁣⁠⁢⁠⁣⁣⁠⁠⁠⁠⁣⁢⁠⁣⁣⁠⁣⁠⁠⁠⁢⁠⁣⁣⁠⁠⁣⁠⁣⁢⁠⁣⁣⁠⁠⁣⁠⁣⁢⁠⁣⁣⁠⁠⁣⁠⁠d myx at 1.98838 SL: 1.883 (1% risk)",
    "structured": "MYX|En⁠⁣⁣⁠⁣⁣⁠⁠⁢⁠⁣⁣⁠⁣⁣⁣⁣⁢⁠⁣⁣⁣⁠⁠⁣⁠⁢⁠⁣⁣⁠⁠⁣⁠⁠⁢⁠⁣⁣⁠⁣⁣⁣⁠⁢⁠⁣⁣⁠⁠⁠⁠⁣⁢⁠⁣⁣⁠⁣⁠⁠⁠⁢⁠⁣⁣⁠⁠⁣⁠⁣⁢⁠⁣⁣⁠⁠⁣⁠⁣⁢⁠⁣⁣⁠⁠⁣⁠⁠try:|1.98838|SL:|1.883"    
}

### Alert signals
POST http://127.0.0.1:8001/api/v1/discord/signal/update
Content-Type: application/json

{
    "discord_id": "1402615865395908659",
    "trader": "@-Tareeq",
    "trade": "1402603117706481710",
    "timestamp": "2025-08-06T11:34:41.653Z",
    "content": " MYX ⁠🚀｜trades⁠: TP1 & stops moved to BE @-Tareeq "
}

