version: '3.8'

services:
  rubicon-trading-bot:
    image: ghcr.io/ngigin/rubicon-trading-bot:latest
    container_name: rubicon-trading-bot
    ports:
      - "8080:8080"
    volumes:
      # Mount logs directory for external access
      - /opt/rubicon/logs:/app/logs
      # Mount environment file
      - /opt/rubicon/.env:/app/.env:ro
    environment:
      - PYTHONPATH=/app
      - TZ=UTC
    env_file:
      - /opt/rubicon/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=10)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - rubicon-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # Optional: Nginx reverse proxy (uncomment if needed)
  # nginx:
  #   image: nginx:alpine
  #   container_name: rubicon-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /opt/rubicon/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - /opt/rubicon/nginx/ssl:/etc/nginx/ssl:ro
  #   restart: unless-stopped
  #   networks:
  #     - rubicon-network
  #   depends_on:
  #     - rubicon-trading-bot
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 128M
  #         cpus: '0.1'

networks:
  rubicon-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: rubicon-br

